receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  prometheus:
    endpoint: '0.0.0.0:8889'
    const_labels:
      collector: 'otel-collector'
extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus]
