apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: greetings-v1-hpa
  namespace: ab-testing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: greetings-v1
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50