apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-v1
  namespace: ab-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings
      version: v1
  template:
    metadata:
      labels:
        app: greetings
        version: v1
    spec:
      containers:
        - name: greetings
          image: jhoeflaken/greetings:1.0
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-v2
  namespace: ab-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings
      version: v2.0
  template:
    metadata:
      labels:
        app: greetings
        version: v2.0
    spec:
      containers:
        - name: greetings
          image: jhoeflaken/greetings:2.0
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: greetings-service
  namespace: ab-testing
spec:
  selector:
    app: greetings
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greetings-ingress
  namespace: ab-testing
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: greetings-service
                port:
                  number: 80