version: '3.7'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'postgres'
    environment:
      POSTGRES_USER:  'postgres'
      POSTGRES_PASSWORD:  ${PASSWORD}
      POSTGRES_DB:  'salescloud'
    ports:
      - "5432:5432"

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@nowhere.com'
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
      PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
    ports:
      - "5050:80"

  activemq:
    image: 'jhoeflaken/artemis:2.32.0'
    container_name: 'activemq'
    environment:
      ARTEMIS_USER: 'admin'
      ARTEMIS_PASSWORD: ${PASSWORD}
      ANONYMOUS_LOGIN: 'true'
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"

  salescloud-event-processor:
    image: 'jhoeflaken/salescloud-event-processor:1.0'
    container_name: 'salescloud-event-processor'
    ports:
      - "8081:8081"
    environment:
      SPRING_ARTEMIS_BROKER_URL: 'tcp://activemq:61616'
      SPRING_ARTEMIS_USER: 'admin'
      SPRING_ARTEMIS_PASSWORD: ${PASSWORD}
    depends_on:
      - activemq

  otel-collector:
    image: ''
    container_name: ''
    ports:
      - "1888:1888"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
    volumes:
      - './docker/otel-collector/otel-collector.yaml:/etc/otel-collector.yaml'
    command:
      - '--config=/etc/otel-collector.yaml'

  prometheus:
    image: ''
    container_name: ''
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - './docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'

  grafana:
    image: ''
    container_name: ''
    volumes:
      - './docker/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml'
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SECURITY_ADMIN_PASSWORD: ${PASSWORD}
      GF_SMTP_ENABLED: 'false'