{
 "title": "Apache Artemis",
 "description": "Dashboard for monitoring Apache Artemis",
 "tags": [ "apache artemis" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(artemis_message_count,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Message Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_message_count{instance=\"$instance\", job=\"artemis\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Connections and Consumers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_connection_count{instance=\"$instance\", job=\"artemis\"}",
     "legendFormat": "Connection Count"
    },
    {
     "expr": "artemis_consumer_count{instance=\"$instance\", job=\"artemis\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Artemis Address Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "artemis_address_size{instance=\"$instance\",job=\"artemis\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "JMV Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\",job=\"artemis\"}",
     "legendFormat": "{{ area }} "
    }
   ]
  }
 ]
}