version: '3.7'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'postgres'
    environment:
      POSTGRES_USER:  'postgres'
      POSTGRES_PASSWORD:  'N3ptun3s'
      POSTGRES_DB:  'salescloud'
    ports:
      - "5432:5432"

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@nowhere.com'
      PGADMIN_DEFAULT_PASSWORD: 'N3ptun3s'
      PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
    ports:
      - "5050:80"

  activemq:
    image: 'jhoeflaken/artemis:2.32.0'
    container_name: 'activemq'
    environment:
      ARTEMIS_USER: 'admin'
      ARTEMIS_PASSWORD: 'N3ptun3s'
      ANONYMOUS_LOGIN: 'true'
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"